config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :camps

end

app/models/camp.rb
class Camp < ActiveRecord::Base
end

app/models/refugee.rb
class Refugee < ActiveRecord::Base
  belongs_to :camp
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  # GET /camps
  # GET /camps.json
  def index
    @camps = Camp.all
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  # GET /camps/new
  def new
    @camp = Camp.new
  end

  # GET /camps/1/edit
  def edit
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to @camp, notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:name, :country, :city, :capacity, :custom_field)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_form.html.erb
<%= form_for(@camp) do |f| %>
  <% if @camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camp.errors.count, "error") %> prohibited this camp from being saved:</h2>

      <ul>
      <% @camp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :custom_field %><br>
    <%= f.text_area :custom_field %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/camps/edit.html.erb
<h1>Editing camp</h1>

<%= render 'form' %>

<%= link_to 'Show', @camp %> |
<%= link_to 'Back', camps_path %>

app/views/camps/index.html.erb
<h1>Listing camps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>City</th>
      <th>Capacity</th>
      <th>Custom field</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @camps.each do |camp| %>
      <tr>
        <td><%= camp.name %></td>
        <td><%= camp.country %></td>
        <td><%= camp.city %></td>
        <td><%= camp.capacity %></td>
        <td><%= camp.custom_field %></td>
        <td><%= link_to 'Show', camp %></td>
        <td><%= link_to 'Edit', edit_camp_path(camp) %></td>
        <td><%= link_to 'Destroy', camp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camp', new_camp_path %>

app/views/camps/new.html.erb
<h1>New camp</h1>

<%= render 'form' %>

<%= link_to 'Back', camps_path %>

app/views/camps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @camp.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @camp.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @camp.city %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @camp.capacity %>
</p>

<p>
  <strong>Custom field:</strong>
  <%= @camp.custom_field %>
</p>

<%= link_to 'Edit', edit_camp_path(@camp) %> |
<%= link_to 'Back', camps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poketeam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>